import type { card } from '@/stores/cardStore'

export const cardsData: card[] = [
  {
    id: 1,
    title: 'Lion',
    description: 'This is the first card',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 1,
    cost: 1,
  },
  {
    id: 2,
    title: 'Tiger',
    description:
      'This is the second card with a longer description to test the layout of the card component and see how it handles longer text content and wraps it. This is the second card with a longer description to test the layout of the card component and see how it handles longer text content and wraps it. This is the second card with a longer description to test the layout of the card component and see how it handles longer text content and wraps it.',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 2,
    cost: 2,
  },
  {
    id: 3,
    title: 'Elephant',
    description: 'This is the third card',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 3,
    cost: 3,
  },
  {
    id: 4,
    title: 'Giraffe',
    description: 'This is the fourth card',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 4,
    cost: 4,
  },
  {
    id: 5,
    title: 'Zebra',
    description: 'This is the fifth card',
    image: 'https://placehold.co/150x100',
    defense: 5,
    attack: 5,
    cost: 5,
  },
  {
    id: 6,
    title: 'Kangaroo',
    description: 'This is the sixth card',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 6,
    cost: 6,
  },
  {
    id: 7,
    title: 'Panda',
    description: 'This is the seventh card',
    image: 'https://placehold.co/150x100',
    defense: 7,
    attack: 7,
    cost: 7,
  },
  {
    id: 8,
    title: 'Koala',
    description: 'This is the eighth card',
    image: 'https://placehold.co/150x100',
    defense: 8,
    attack: 8,
    cost: 8,
  },
  {
    id: 9,
    title: 'Penguin',
    description: 'This is the ninth card',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 9,
    cost: 9,
  },
  {
    id: 10,
    title: 'Dolphin',
    description: 'This is the tenth card',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 10,
    cost: 10,
  },
  {
    id: 11,
    title: 'Whale',
    description: 'This is the eleventh card',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 3,
    cost: 3,
  },
  {
    id: 12,
    title: 'Shark',
    description: 'This is the twelfth card',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 3,
    cost: 3,
  },
  {
    id: 13,
    title: 'Cheetah',
    description: 'This is card number 13',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 8,
    cost: 10,
  },
  {
    id: 14,
    title: 'Leopard',
    description: 'This is card number 14',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 7,
    cost: 11,
  },
  {
    id: 15,
    title: 'Wolf',
    description: 'This is card number 15',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 4,
    cost: 10,
  },
  {
    id: 16,
    title: 'Fox',
    description: 'This is card number 16',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 3,
    cost: 11,
  },
  {
    id: 17,
    title: 'Bear',
    description: 'This is card number 17',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 10,
    cost: 2,
  },
  {
    id: 18,
    title: 'Rabbit',
    description: 'This is card number 18',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 0,
    cost: 7,
  },
  {
    id: 19,
    title: 'Deer',
    description: 'This is card number 19',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 8,
    cost: 9,
  },
  {
    id: 20,
    title: 'Moose',
    description: 'This is card number 20',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 2,
    cost: 10,
  },
  {
    id: 21,
    title: 'Bison',
    description: 'This is card number 21',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 9,
    cost: 10,
  },
  {
    id: 22,
    title: 'Buffalo',
    description: 'This is card number 22',
    image: 'https://placehold.co/150x100',
    defense: 7,
    attack: 1,
    cost: 9,
  },
  {
    id: 23,
    title: 'Camel',
    description: 'This is card number 23',
    image: 'https://placehold.co/150x100',
    defense: 8,
    attack: 6,
    cost: 10,
  },
  {
    id: 24,
    title: 'Horse',
    description: 'This is card number 24',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 8,
    cost: 10,
  },
  {
    id: 25,
    title: 'Donkey',
    description: 'This is card number 25',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 3,
    cost: 7,
  },
  {
    id: 26,
    title: 'Goat',
    description: 'This is card number 26',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 2,
    cost: 10,
  },
  {
    id: 27,
    title: 'Sheep',
    description: 'This is card number 27',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 7,
    cost: 10,
  },
  {
    id: 28,
    title: 'Pig',
    description: 'This is card number 28',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 4,
    cost: 10,
  },
  {
    id: 29,
    title: 'Cow',
    description: 'This is card number 29',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 7,
    cost: 9,
  },
  {
    id: 30,
    title: 'Chicken',
    description: 'This is card number 30',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 6,
    cost: 11,
  },
  {
    id: 31,
    title: 'Duck',
    description: 'This is card number 31',
    image: 'https://placehold.co/150x100',
    defense: 5,
    attack: 9,
    cost: 8,
  },
  {
    id: 32,
    title: 'Goose',
    description: 'This is card number 32',
    image: 'https://placehold.co/150x100',
    defense: 5,
    attack: 3,
    cost: 9,
  },
  {
    id: 33,
    title: 'Turkey',
    description: 'This is card number 33',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 9,
    cost: 5,
  },
  {
    id: 34,
    title: 'Ostrich',
    description: 'This is card number 34',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 8,
    cost: 8,
  },
  {
    id: 35,
    title: 'Peacock',
    description: 'This is card number 35',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 2,
    cost: 7,
  },
  {
    id: 36,
    title: 'Parrot',
    description: 'This is card number 36',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 0,
    cost: 4,
  },
  {
    id: 37,
    title: 'Eagle',
    description: 'This is card number 37',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 9,
    cost: 10,
  },
  {
    id: 38,
    title: 'Hawk',
    description: 'This is card number 38',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 7,
    cost: 10,
  },
  {
    id: 39,
    title: 'Falcon',
    description: 'This is card number 39',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 5,
    cost: 6,
  },
  {
    id: 40,
    title: 'Owl',
    description: 'This is card number 40',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 9,
    cost: 10,
  },
  {
    id: 41,
    title: 'Sparrow',
    description: 'This is card number 41',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 2,
    cost: 5,
  },
  {
    id: 42,
    title: 'Robin',
    description: 'This is card number 42',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 8,
    cost: 11,
  },
  {
    id: 43,
    title: 'Blue Jay',
    description: 'This is card number 43',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 8,
    cost: 10,
  },
  {
    id: 44,
    title: 'Cardinal',
    description: 'This is card number 44',
    image: 'https://placehold.co/150x100',
    defense: 8,
    attack: 4,
    cost: 9,
  },
  {
    id: 45,
    title: 'Finch',
    description: 'This is card number 45',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 7,
    cost: 4,
  },
  {
    id: 46,
    title: 'Swan',
    description: 'This is card number 46',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 1,
    cost: 9,
  },
  {
    id: 47,
    title: 'Flamingo',
    description: 'This is card number 47',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 9,
    cost: 5,
  },
  {
    id: 48,
    title: 'Pelican',
    description: 'This is card number 48',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 4,
    cost: 10,
  },
  {
    id: 49,
    title: 'Seagull',
    description: 'This is card number 49',
    image: 'https://placehold.co/150x100',
    defense: 8,
    attack: 5,
    cost: 10,
  },
  {
    id: 51,
    title: 'Crane',
    description: 'This is card number 51',
    image: 'https://placehold.co/150x100',
    defense: 5,
    attack: 6,
    cost: 7,
  },
  {
    id: 52,
    title: 'Heron',
    description: 'This is card number 52',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 5,
    cost: 6,
  },
  {
    id: 53,
    title: 'Stork',
    description: 'This is card number 53',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 4,
    cost: 5,
  },
  {
    id: 54,
    title: 'Ibis',
    description: 'This is card number 54',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 3,
    cost: 4,
  },
  {
    id: 55,
    title: 'Egret',
    description: 'This is card number 55',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 2,
    cost: 3,
  },
  {
    id: 56,
    title: 'Bittern',
    description: 'This is card number 56',
    image: 'https://placehold.co/150x100',
    defense: 0,
    attack: 1,
    cost: 2,
  },
  {
    id: 57,
    title: 'Kingfisher',
    description: 'This is card number 57',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 7,
    cost: 8,
  },
  {
    id: 58,
    title: 'Woodpecker',
    description: 'This is card number 58',
    image: 'https://placehold.co/150x100',
    defense: 7,
    attack: 8,
    cost: 9,
  },
  {
    id: 59,
    title: 'Hummingbird',
    description: 'This is card number 59',
    image: 'https://placehold.co/150x100',
    defense: 8,
    attack: 9,
    cost: 10,
  },
  {
    id: 60,
    title: 'Swift',
    description: 'This is card number 60',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 10,
    cost: 11,
  },
  {
    id: 61,
    title: 'Swallow',
    description: 'This is card number 61',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 0,
    cost: 1,
  },
  {
    id: 62,
    title: 'Martlet',
    description: 'This is card number 62',
    image: 'https://placehold.co/150x100',
    defense: 0,
    attack: 1,
    cost: 2,
  },
  {
    id: 63,
    title: 'Nightingale',
    description: 'This is card number 63',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 2,
    cost: 3,
  },
  {
    id: 64,
    title: 'Lark',
    description: 'This is card number 64',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 3,
    cost: 4,
  },
  {
    id: 65,
    title: 'Wren',
    description: 'This is card number 65',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 4,
    cost: 5,
  },
  {
    id: 66,
    title: 'Dove',
    description: 'This is card number 66',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 5,
    cost: 6,
  },
  {
    id: 67,
    title: 'Pigeon',
    description: 'This is card number 67',
    image: 'https://placehold.co/150x100',
    defense: 5,
    attack: 6,
    cost: 7,
  },
  {
    id: 68,
    title: 'Quail',
    description: 'This is card number 68',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 7,
    cost: 8,
  },
  {
    id: 69,
    title: 'Partridge',
    description: 'This is card number 69',
    image: 'https://placehold.co/150x100',
    defense: 7,
    attack: 8,
    cost: 9,
  },
  {
    id: 70,
    title: 'Pheasant',
    description: 'This is card number 70',
    image: 'https://placehold.co/150x100',
    defense: 8,
    attack: 9,
    cost: 10,
  },
  {
    id: 71,
    title: 'Grouse',
    description: 'This is card number 71',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 10,
    cost: 11,
  },
  {
    id: 72,
    title: 'Ptarmigan',
    description: 'This is card number 72',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 0,
    cost: 1,
  },
  {
    id: 73,
    title: 'Sandpiper',
    description: 'This is card number 73',
    image: 'https://placehold.co/150x100',
    defense: 0,
    attack: 1,
    cost: 2,
  },
  {
    id: 74,
    title: 'Snipe',
    description: 'This is card number 74',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 2,
    cost: 3,
  },
  {
    id: 75,
    title: 'Woodcock',
    description: 'This is card number 75',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 3,
    cost: 4,
  },
  {
    id: 76,
    title: 'Curlew',
    description: 'This is card number 76',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 4,
    cost: 5,
  },
  {
    id: 77,
    title: 'Avocet',
    description: 'This is card number 77',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 5,
    cost: 6,
  },
  {
    id: 78,
    title: 'Oystercatcher',
    description: 'This is card number 78',
    image: 'https://placehold.co/150x100',
    defense: 5,
    attack: 6,
    cost: 7,
  },
  {
    id: 79,
    title: 'Lapwing',
    description: 'This is card number 79',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 7,
    cost: 8,
  },
  {
    id: 80,
    title: 'Plover',
    description: 'This is card number 80',
    image: 'https://placehold.co/150x100',
    defense: 7,
    attack: 8,
    cost: 9,
  },
  {
    id: 81,
    title: 'Dotterel',
    description: 'This is card number 81',
    image: 'https://placehold.co/150x100',
    defense: 8,
    attack: 9,
    cost: 10,
  },
  {
    id: 82,
    title: 'Turnstone',
    description: 'This is card number 82',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 10,
    cost: 11,
  },
  {
    id: 83,
    title: 'Redshank',
    description: 'This is card number 83',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 0,
    cost: 1,
  },
  {
    id: 84,
    title: 'Greenshank',
    description: 'This is card number 84',
    image: 'https://placehold.co/150x100',
    defense: 0,
    attack: 1,
    cost: 2,
  },
  {
    id: 85,
    title: 'Godwit',
    description: 'This is card number 85',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 2,
    cost: 3,
  },
  {
    id: 86,
    title: 'Ruff',
    description: 'This is card number 86',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 3,
    cost: 4,
  },
  {
    id: 87,
    title: 'Phalarope',
    description: 'This is card number 87',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 4,
    cost: 5,
  },
  {
    id: 88,
    title: 'Skua',
    description: 'This is card number 88',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 5,
    cost: 6,
  },
  {
    id: 89,
    title: 'Gull',
    description: 'This is card number 89',
    image: 'https://placehold.co/150x100',
    defense: 5,
    attack: 6,
    cost: 7,
  },
  {
    id: 90,
    title: 'Tern',
    description: 'This is card number 90',
    image: 'https://placehold.co/150x100',
    defense: 6,
    attack: 7,
    cost: 8,
  },
  {
    id: 91,
    title: 'Auk',
    description: 'This is card number 91',
    image: 'https://placehold.co/150x100',
    defense: 7,
    attack: 8,
    cost: 9,
  },
  {
    id: 92,
    title: 'Puffin',
    description: 'This is card number 92',
    image: 'https://placehold.co/150x100',
    defense: 8,
    attack: 9,
    cost: 10,
  },
  {
    id: 93,
    title: 'Guillemot',
    description: 'This is card number 93',
    image: 'https://placehold.co/150x100',
    defense: 9,
    attack: 10,
    cost: 11,
  },
  {
    id: 94,
    title: 'Razorbill',
    description: 'This is card number 94',
    image: 'https://placehold.co/150x100',
    defense: 10,
    attack: 0,
    cost: 1,
  },
  {
    id: 95,
    title: 'Dovekie',
    description: 'This is card number 95',
    image: 'https://placehold.co/150x100',
    defense: 0,
    attack: 1,
    cost: 2,
  },
  {
    id: 96,
    title: 'Murres',
    description: 'This is card number 96',
    image: 'https://placehold.co/150x100',
    defense: 1,
    attack: 2,
    cost: 3,
  },
  {
    id: 97,
    title: 'Penguin',
    description: 'This is card number 97',
    image: 'https://placehold.co/150x100',
    defense: 2,
    attack: 3,
    cost: 4,
  },
  {
    id: 98,
    title: 'Petrel',
    description: 'This is card number 98',
    image: 'https://placehold.co/150x100',
    defense: 3,
    attack: 4,
    cost: 5,
  },
  {
    id: 99,
    title: 'Shearwater',
    description: 'This is card number 99',
    image: 'https://placehold.co/150x100',
    defense: 4,
    attack: 5,
    cost: 6,
  },
  {
    id: 100,
    title: 'Storm-petrel',
    description: 'This is card number 100',
    image: 'https://placehold.co/150x100',
    defense: 5,
    attack: 6,
    cost: 7,
  },
]
// function getRandomInt(min: number, max: number): number {
//   return Math.floor(Math.random() * (max - min + 1)) + min
// }

// for (let i = 13; i <= 50; i++) {
//   const defense = getRandomInt(0, 10)
//   const cost = getRandomInt(defense + 1, 10)
//   const attack = getRandomInt(0, 10)

//   cardsData.push({
//     title: `Card ${i}`,
//     description: `This is card number ${i}`,
//     image: 'https://placehold.co/150x100',
//     defense,
//     attack,
//     cost,
//   })
// }
